# Generated by Django 3.1.1 on 2023-12-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20231229_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='end_date',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='start_date',
            new_name='start_year',
        ),
    ]
