# Generated by Django 3.1.1 on 2023-12-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20231229_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='end_year',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='start_year',
            new_name='start_date',
        ),
    ]
